CONF_THRESHOLD = 0.25
NMS_THRESHOLD  = 0.45
INPUT_SIZE     = 320

DEPTH_EVERY_N  = 3
DETECT_EVERY_N = 5
STAIRS_EVERY_N = 7

NUM_DISPARITIES = 128
BLOCK_SIZE      = 5

DISTANCE_EMA_ALPHA = 0.3

ALERT_DISTANCE = 1.0 # metres